name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # AÑADE ESTE NUEVO PASO AQUÍ
      - name: Configurar Node.js y PNPM
        uses: actions/setup-node@v4
        with:
          node-version: '22.15' # <-- IMPORTANTE: Pon aquí la versión de Node.js que usa tu proyecto (e.g., '16', '18', '20')
          cache: 'pnpm'     # <-- ESTO ES CLAVE: Le dice a la acción que instale y configure pnpm

      # OPCIONAL PERO RECOMENDADO: Instalar tus dependencias
      - name: Instalar dependencias
        run: pnpm install # Asegúrate de que todas las dependencias de tu proyecto estén instaladas

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: pnpm start # Ahora pnpm debería estar disponible
          wait-on: 'http://localhost:5173'
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
