name: Cypress Tests
on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js with PNPM
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Ajusta a la versión de Node.js de tu proyecto

      - name: Install dependencies # Instala las dependencias del proyecto (incluyendo las de Cypress)
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          config: baseUrl=https://rick-morty-39iyxpr96-crisky94s-projects.vercel.app/
          record: true
          parallel: true
        env:
          $ cypress run --record --key <record_key>
